name = "Wakame"
uuid = "4447db07-3941-47e2-90a2-965b7cb1b6ce"
authors = ["Bernard Brenyah"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
